---
# defaults file for roles/vault-init
unseal_keys_dir_output: "{{ playbook_dir }}/unsealKey"
root_token_dir_output: "{{ playbook_dir }}/rootKey"
vault_addr: "http://{{ ansible_eth0.ipv4.address }}:8200"